= Approval Testing Tooling

This library provides some tooling to do Approval Testing on top of PHPUnit.


== What you can do with it

:leveloffset: +2

= Generate Combinations

`Combination::generate` method creates combinations from multiple list of values.

The method returns an array of combinations and uses a descriptive key for each one of them.

Use this in a PhpUnit data provider.

== Examples

[source,php]
----
Combination::generate([1,2,3],[A]);

array (
  '1 A' =>
  array (
    0 => 1,
    1 => 'A',
  ),
  '2 A' =>
  array (
    0 => 2,
    1 => 'A',
  ),
  '3 A' =>
  array (
    0 => 3,
    1 => 'A',
  ),
)
----

[source,php]
----
Combination::generate([1,2],[A,B]);

array (
  '1 A' =>
  array (
    0 => 1,
    1 => 'A',
  ),
  '1 B' =>
  array (
    0 => 1,
    1 => 'B',
  ),
  '2 A' =>
  array (
    0 => 2,
    1 => 'A',
  ),
  '2 B' =>
  array (
    0 => 2,
    1 => 'B',
  ),
)
----

[source,php]
----
Combination::generate([1,2],[X,Y,Z],[A,B]);

array (
  '1 X A' =>
  array (
    0 => 1,
    1 => 'X',
    2 => 'A',
  ),
  '1 X B' =>
  array (
    0 => 1,
    1 => 'X',
    2 => 'B',
  ),
  '1 Y A' =>
  array (
    0 => 1,
    1 => 'Y',
    2 => 'A',
  ),
  '1 Y B' =>
  array (
    0 => 1,
    1 => 'Y',
    2 => 'B',
  ),
  '1 Z A' =>
  array (
    0 => 1,
    1 => 'Z',
    2 => 'A',
  ),
  '1 Z B' =>
  array (
    0 => 1,
    1 => 'Z',
    2 => 'B',
  ),
  '2 X A' =>
  array (
    0 => 2,
    1 => 'X',
    2 => 'A',
  ),
  '2 X B' =>
  array (
    0 => 2,
    1 => 'X',
    2 => 'B',
  ),
  '2 Y A' =>
  array (
    0 => 2,
    1 => 'Y',
    2 => 'A',
  ),
  '2 Y B' =>
  array (
    0 => 2,
    1 => 'Y',
    2 => 'B',
  ),
  '2 Z A' =>
  array (
    0 => 2,
    1 => 'Z',
    2 => 'A',
  ),
  '2 Z B' =>
  array (
    0 => 2,
    1 => 'Z',
    2 => 'B',
  ),
)
----


= Scrub non-deterministic value

If you are not able to get reproductible output for tests you can use Scrubbers to transform a non-deterministic output to a deterministic.

Scrubbers are tools that takes a string and returns a string. You can combine multiple scrubbers together if needed.

:leveloffset: +1

= Scrub UUIDs

The `UuidScrubber` replaces all UUID found in a string by a simpler string.

It also ensures that if the same UUID is found multiple times in the same string the same replacement string is used.

== Examples

[%unbreakable]
[source,php]
----
        $inputString = <<<EOS
Here is a 5c2068a8-7213-42f6-81d7-ef3a270d7bd1,
and here is another one 52276882-9853-4e3d-9e8d-c54c77db03a4
EOS;

        $uuidScrubber = new UuidScrubber();

        $scrubbedText = $uuidScrubber->scrub($inputString);
----

produces

[%unbreakable]
----
Here is a UUID_0,
and here is another one UUID_1
----

The following example shows that multiple occurrences of the same UUID are replaced with the same value :

[%unbreakable]
[source,php]
----
        $inputString = <<<EOS
Here is a 5c2068a8-7213-42f6-81d7-ef3a270d7bd1,
and here is another one 52276882-9853-4e3d-9e8d-c54c77db03a4,
and here is the first one again 5c2068a8-7213-42f6-81d7-ef3a270d7bd1
EOS;

        $uuidScrubber = new UuidScrubber();

        $scrubbedText = $uuidScrubber->scrub($inputString);
----

produces

[%unbreakable]
----
Here is a UUID_0,
and here is another one UUID_1,
and here is the first one again UUID_0
----

:leveloffset: -1

:leveloffset: -2
