name: Build Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
    name: PhpUnit ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: "ramsey/composer-install@v2"
      - name: Print version
        run: php -v
      - name: Run tests
        run: ./vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PhpStan
        uses: php-actions/phpstan@v3
